name = "UniversalWord"
version = "0.1.0"
defaultTargets = ["WordDialect", "WordIR", "Forth", "BCPL", "Wolfram", "Harness", "X86", "wordc", "Wasm", "wasmw"]

[[lean_lib]]
name = "WordDialect"
srcDir = "formal"

[[lean_lib]]
name = "WordIR"
srcDir = "word-ir"

[[lean_lib]]
name = "Forth"
srcDir = "forth"

[[lean_lib]]
name = "BCPL"
srcDir = "bcpl"

[[lean_lib]]
name = "Wolfram"
srcDir = "wolfram"

[[lean_lib]]
name = "X86"
srcDir = "backend/x86_64"

[[lean_exe]]
name = "wordc"
root = "Main"
srcDir = "backend/x86_64"

[[lean_lib]]
name = "Harness"
srcDir = "backend/common"

[[lean_lib]]
name = "Wasm"
srcDir = "backend/wasm"

[[lean_exe]]
name = "wasmw"
root = "WasmMain"
srcDir = "backend/wasm"
