name = "UniversalWord"
version = "0.1.0"
defaultTargets = ["WordDialect", "WordIR", "Forth", "BCPL", "Wolfram", "Harness", "X86", "wordc", "Wasm", "wasmw", "A64", "a64c", "RV", "rv64c", "RV32", "rv32c", "CM", "cmc", "CM0", "cm0c"]

[[lean_lib]]
name = "WordDialect"
srcDir = "formal"

[[lean_lib]]
name = "WordIR"
srcDir = "word-ir"

[[lean_lib]]
name = "Forth"
srcDir = "forth"

[[lean_lib]]
name = "BCPL"
srcDir = "bcpl"

[[lean_lib]]
name = "Wolfram"
srcDir = "wolfram"

[[lean_lib]]
name = "X86"
srcDir = "backend/x86_64"

[[lean_exe]]
name = "wordc"
root = "Main"
srcDir = "backend/x86_64"

[[lean_lib]]
name = "Harness"
srcDir = "backend/common"
roots = ["Harness", "Harness32"]

[[lean_lib]]
name = "Wasm"
srcDir = "backend/wasm"

[[lean_exe]]
name = "wasmw"
root = "WasmMain"
srcDir = "backend/wasm"

[[lean_lib]]
name = "A64"
srcDir = "backend/arm64"

[[lean_exe]]
name = "a64c"
root = "A64Main"
srcDir = "backend/arm64"

[[lean_lib]]
name = "RV"
srcDir = "backend/riscv64"

[[lean_exe]]
name = "rv64c"
root = "RVMain"
srcDir = "backend/riscv64"

[[lean_lib]]
name = "RV32"
srcDir = "backend/rv32"

[[lean_exe]]
name = "rv32c"
root = "RV32Main"
srcDir = "backend/rv32"

[[lean_lib]]
name = "CM"
srcDir = "backend/cortexm"

[[lean_exe]]
name = "cmc"
root = "CMMain"
srcDir = "backend/cortexm"

[[lean_lib]]
name = "CM0"
srcDir = "backend/cortexm0"

[[lean_exe]]
name = "cm0c"
root = "CM0Main"
srcDir = "backend/cortexm0"
