\ VARIABLE, CONSTANT, MOD, 0=, RECURSE and EXIT. Halts with 21 (gcd) and 1.
10 CONSTANT TEN
VARIABLE RESULT
: GCD ( a b -- g )  DUP 0= IF DROP EXIT THEN  SWAP OVER MOD RECURSE ;
1071 462 GCD RESULT !
RESULT @   TEN 3 MOD 1 =  IF 1 ELSE 0 THEN
